### ISSUE TITLE
exit status 1

### ISSUE THREAD

**Issue by cukkk** [ctaoist/clashweblite#1]
错误，系统找不到指定的注册表项或值。exit status 1

**Comment by cukkk** [comment]
![111](https://user-images.githubusercontent.com/19454186/164886746-86d5fdff-be99-4f95-b639-7db42f710870.jpg)

**Comment by cukkk** [comment]
http://127.0.0.1:9090/ui/ 也打不开

**Comment by ctaoist** [comment]
你这系统应该是win7，我在win7测试也提示这个，虽然提示了这个，但功能都是正常的。应该是在win7上查注册表，查不到相应的值会返回错误，但在win10上就不会返回错误。

**Comment by cukkk** [comment]
用win10测试也有提示的，是不是运行就要加开机启动？

**Comment by cukkk** [comment]
其实不需要运行就加入系统启动项，可以在右下角点击选择

**Comment by ctaoist** [comment]
是检测当前是否设置成开机启动，这个不会自动设置

刚测试了一下，最新的release确实都会提示，我优化一下

**Comment by cukkk** [comment]
好的，辛苦了

**Comment by ctaoist** [comment]
ok了

**Comment by cukkk** [comment]
谢谢！
