### ISSUE TITLE
增加依赖提示

### ISSUE THREAD

**Issue by panglars** [ctaoist/clashweblite#3]
环境:ArchLinux xfce4
初次启动报错
``` 
./clashweb: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
```
Linux下使用需要安装[libayatana-appindicator](https://github.com/AyatanaIndicators/libayatana-appindicator)依赖

**Comment by ctaoist** [comment]
好的，linux发行版及桌面环境太多，测试难以覆盖完全
